### ISSUE TITLE
Include a standard "ILIKE" search

### ISSUE THREAD

**Issue by djsegal** [Casecommons/pg_search#356] opened 2017-04-09 04:04 UTC
Currently something like:

```
@core_query.where \
          "name ILIKE ?", "%#{ search_param }%"
```

will catch some values not found by:

+ tsearch
+ trigram
+ dmetaphone

**Comment by tostrio** [comment] 2017-05-15 23:39
Would also like this. `pg_search` is super readable and easy to use compared to other association-search-solutions.

**Comment by nertzy** [comment] 2017-05-16 15:03
Duplicate of #3

**Closed by nertzy** 2017-05-16 15:03 UTC
