### ISSUE TITLE
Deploying with Capistrano 

### ISSUE THREAD

**Issue by zreitano** [Casecommons/pg_search#144] opened 2013-11-21 17:20 UTC
Everything works perfectly locally. 

When deploying with capistrano (using unicorn & nginx) I receive the error "Uninitialized  constant ModelName::PgSearch (NameError). 

First time deploying pg_search in production. 

Any help would be appreciated.

**Comment by giedriusr** [comment] 2015-02-03 15:02
Implemented pg_search locally, everything works fine. Haven't deploy to production with capistrano yet, but will post the results no matter how it goes.

**Comment by rcchen** [comment] 2015-02-09 07:11
I am also getting the same issue using Capistrano to deploy a Rails application; what I find to be rather strange is that the gem is installed correctly in `shared/bundle/ruby/2.2.0/gems/pg_search-0.7.9`. I will be attempting to remedy this issue somehow and will update if I find a solution.

**Comment by rcchen** [comment] 2015-02-09 07:22
Alright, I have absolutely no idea why this worked, but it did.

1. Added `require 'pg_search'` to config/boot.rb
2. Deployed it via Capistrano and hit a 502 Bad Gateway issue.
3. Rolled back the change, re-deployed, and everything works now?!?

Definitely would appreciate any additional insight anyone might have into this; otherwise, I'm not complaining.

**Comment by nertzy** [comment] 2015-05-14 02:20
Closing this issue because it seems to be sporadic in nature. I'm not convinced it's something that requires any sort of change to pg_search.

**Closed by nertzy** 2015-05-14 02:20 UTC

**Comment by jashwant** [comment] 2015-09-27 04:09
Same problem on my local development machine. Restarted the server, after installing gem. Works fine now.

**Comment by syzygy333** [comment] 2015-10-15 14:26
Same problem here, except the issue is arising in development. It happens on all of my models. Everything was working on the branch I was working on 5 minutes ago. Nothing regarding pg_search has changed in those 5 minutes. I tried adding `require 'pg_search'` to no avail. I restarted the server several times. I updated iTerm. Nothing works.

**Comment by johnmhenson** [comment] 2016-02-07 19:16
Same issue in development - restarted server after error.  Works fine.

**Comment by Gabony** [comment] 2019-09-30 22:32
For those who need the link of syzygy333 : https://web.archive.org/web/20150426101534/https://hackhands.com/rails-nameerror-uninitialized-constant-class-solution/
