### ISSUE TITLE
Using curly quotes in search  string generates invalid SQL error

### ISSUE THREAD

**Issue by patrick-gleeson** [Casecommons/pg_search#390] opened 2018-10-20 11:31 UTC
If your record is, e.g.:

```ruby
class Post < ApplicationRecord
  include PgSearch
  attribute :title, :string
  pg_search_scope :test_search, against: [:title],
                  ignoring: :accents
end
```

And then you call it using the following (note the curly quote):
```ruby
Post.test_search "O’Reilly"
```
You will get this error:
```
ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  syntax error in tsquery: "' Reilly '")
```
The generated SQL is:
```sql
SELECT  "posts".* FROM "posts" INNER JOIN (SELECT "posts"."id" AS pg_search_id, (ts_rank((to_tsvector('simple', unaccent(coalesce("posts"."title"::text, '')))), (to_tsquery('simple', ''' ' || unaccent('O’Reilly') || ' ''')), 0)) AS rank FROM "posts" WHERE (((to_tsvector('simple', unaccent(coalesce("posts"."title"::text, '')))) @@ (to_tsquery('simple', ''' ' || unaccent('O’Reilly') || ' '''))))) AS pg_search_6e317bcd6839e887739541 ON "posts"."id" = pg_search_6e317bcd6839e887739541.pg_search_id ORDER BY pg_search_6e317bcd6839e887739541.rank DESC, "posts"."id" ASC LIMIT $1
```

This happens because the output of `unaccent('O’Reilly')` is `'O'Reilly'`, i.e. the curly quote becomes a straight quote, and therefore `to_tsquery('simple', ''' ' || unaccent('O’Reilly') || ' ''')` becomes `to_tsquery('simple', ''' O'Reilly ''')`, which has an unescaped quote in it.

Note that if you call `Post.test_search "O'Reilly"` (note the straight quote), the generate SQL contains `unaccent('O Reilly')`, i.e. the single quote is removed. Therefore I believe the root problem is that the code is stripping straight single quotes but not curly single quotes when generating the `unaccent` string fragment.

**Comment by patrick-gleeson** [comment] 2018-11-05 15:22
Looks like this has already been fixed in `master` (commit at https://github.com/Casecommons/pg_search/commit/4ad6a135f5ab04d8609ff08e70d3dab93042afb6), just hasn't been released yet.

**Comment by amarshall** [comment] 2018-12-09 17:12
Duplicate of https://github.com/Casecommons/pg_search/pull/385.

**Closed by amarshall** 2018-12-09 17:12 UTC
