### ISSUE TITLE
hash column

### ISSUE THREAD

**Issue by mm580486** [Casecommons/pg_search#328] opened 2016-10-02 15:05 UTC
Hello, people have had trouble searching in hash column not return god result 
my column name is properties ( for dynamic field ) and not returning good result :(

**Comment by nertzy** [comment] 2016-12-21 15:37
Closing due to lack of specific information.

If you want to re-open an issue, please give code examples, expected behavior, and actual behavior.

**Closed by nertzy** 2016-12-21 15:37 UTC
