### ISSUE TITLE
possible to use a method in model as column 

### ISSUE THREAD

**Issue by jgrannas** [Casecommons/pg_search#212] opened 2015-01-25 21:18 UTC
First I tried this… which did not work

```ruby
multisearchable against: [:title, :desc, :details],  associated_against: { brand: :name }
```

Is it possible to use something like this, to allow pg_search to index off the brand/tags of a product. Or what is the best approach to do something like this?

```ruby
class Product 
    
    has_and_belongs_to_many :tags
    belongs_to :brand

    multisearchable against: [:title, :desc, :details, :brand_name, :tag_names]

    def brand_name
        brand.name
    end

    def tag_names
        tags.pluck(:name).join(", ")
    end
end
```

ran the associated_against migration as directed, and then rebuilt my index on Product, but i don't see the brand names being added to teh content column of the search index table

EDIT: I got this to work by adding the naive approach update method in the model

```ruby
def self.rebuild_pg_search_documents
    find_each { |record| record.update_pg_search_document }
end
```

It would not work with the `rake pg_search:multisearch:rebuild[Product]`, but worked fine using this method. Hopefully this is the proper way to approach this. It makes sense, as it the methods do not exist in a query/SQL.

THIS GEM ROCKS.

**Comment by nertzy** [comment] 2015-04-14 13:22
Yes, your usage should be working fine without the naive approach.

I think this is the same issue as in #214 so I am closing this one out to save space. Let me know if that's an incorrect assumption. Thanks!

**Closed by nertzy** 2015-04-14 13:22 UTC

**Comment by amarshall** [comment] 2015-09-09 05:11
Duplicate of #157
